repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
        minimum_pre_commit_version: "2.9.0"
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]
      - id: flake8
        name: flake8
        language: system
        entry: flake8
        require_serial: true
        types: [python]
      - id: pyright
        name: pyright
        language: system
        entry: pyright
        require_serial: true
        types: [python]
